import { test, expect } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import { join } from 'node:path';

test('income source persists through draft, save and edit and appears in the monthly breakdown', async ({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.clock.setFixedTime(new Date('2026-10-04T12:00:00Z'));
 await page.goto('/#/add');
 await page.getByRole('button',{name:'收入',exact:true}).click();
 await page.getByLabel('收入來源').fill('游泳教班');
 await page.getByRole('navigation',{name:'主要導航'}).getByRole('button',{name:'總覽',exact:true}).click();
 await page.getByRole('navigation',{name:'主要導航'}).getByRole('button',{name:'記帳',exact:true}).click();
 await expect(page.getByLabel('收入來源')).toHaveValue('游泳教班');
 await page.getByRole('button',{name:'輸入金額'}).click();
 for(const n of ['1','0','0']) await page.getByRole('button',{name:n,exact:true}).click();
 await page.getByRole('button',{name:'完成輸入'}).click();
 await page.getByRole('button',{name:'工作',exact:true}).click();
 await page.getByRole('button',{name:'儲存',exact:true}).click();
 await expect(page).toHaveURL(/#\/records$/);
 await page.goto('/#/planning?tab=income');
 await expect(page.getByTestId('income-total')).toContainText('100');
 await page.getByText('游泳教班',{exact:true}).click();
 await page.getByRole('button',{name:/收入帳目/}).click();
 await page.getByRole('button',{name:'編輯',exact:true}).click();
 await page.getByLabel('收入來源').fill('私人教班');
 await page.getByRole('button',{name:'儲存',exact:true}).click();
 await page.goto('/#/planning?tab=income');await page.reload();
 await expect(page.getByText('私人教班',{exact:true})).toBeVisible();
 await expect(page.getByText('游泳教班',{exact:true})).toHaveCount(0);
 const dir=join(process.env.RUNNER_TEMP || '/tmp','smartfinance-ui');await mkdir(dir,{recursive:true});
 await page.screenshot({path:join(dir,`${info.project.name}-income.png`),animations:'disabled'});
 await page.getByLabel('規劃幣別').selectOption('AUD');
 await expect(page.getByTestId('income-total')).toContainText('0');
 expect(errors).toEqual([]);
});

test('annual reserve CRUD, rollover and currency isolation do not create spending',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.clock.setFixedTime(new Date('2026-10-04T12:00:00Z'));
 await page.addInitScript(()=>{localStorage.setItem('smartfinance_themecolor','applefluid-system');localStorage.setItem('smartfinance_has_onboarded','true');});
 await page.goto('/#/');
 await page.getByRole('button',{name:'年度支出預留',exact:true}).click();
 await page.getByLabel('規劃幣別').selectOption('AUD');
 await page.getByRole('button',{name:'新增年度項目'}).click();
 await page.getByLabel('年度項目名稱').fill('車保');
 await page.getByLabel('目標金額',{exact:true}).fill('1200');
 await page.getByLabel('已預留金額',{exact:true}).fill('200');
 await page.getByLabel('下次到期日').fill('2027-02-15');
 await page.getByRole('button',{name:'儲存年度項目'}).click();
 await expect(page.getByRole('dialog')).toHaveCount(0);
 await expect(page.getByTestId('reserve-monthly')).toContainText('250');
 await page.reload();await page.getByLabel('規劃幣別').selectOption('AUD');
 await expect(page.getByRole('heading',{name:'車保',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'編輯車保',exact:true}).click();
 await page.getByLabel('已預留金額').fill('400');
 await page.getByRole('button',{name:'儲存年度項目'}).click();
 await expect(page.getByTestId('reserve-monthly')).toContainText('200');
 const dir=join(process.env.RUNNER_TEMP || '/tmp','smartfinance-ui');await mkdir(dir,{recursive:true});
 for(const theme of ['light','dark'] as const){await page.emulateMedia({colorScheme:theme});await page.screenshot({path:join(dir,`${info.project.name}-planning-${theme}.png`),animations:'disabled'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
 await page.getByLabel('規劃幣別').selectOption('HKD');await expect(page.getByTestId('reserve-monthly')).toContainText('0');
 await page.getByLabel('規劃幣別').selectOption('AUD');
 await page.getByRole('button',{name:'開始下一年',exact:true}).click();
 await page.getByRole('alertdialog').getByRole('button',{name:'開始下一年',exact:true}).click();
 await expect(page.getByText('到期 2028-02-15',{exact:true})).toBeVisible();
 await expect(page.getByRole('progressbar')).toHaveAttribute('value','0');
 await page.getByRole('button',{name:'刪除',exact:true}).click();
 await page.getByRole('alertdialog').getByRole('button',{name:'刪除',exact:true}).click();
 await expect(page.getByRole('heading',{name:'車保',exact:true})).toHaveCount(0);
 await page.goto('/#/records');await expect(page.locator('.sf-record-row')).toHaveCount(0);
 expect(errors).toEqual([]);
});
