import { expect, test } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import { join } from 'node:path';

test('service picker filters, preserves form when returning, and saves a branded subscription', async ({ page }, info) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await page.addInitScript(() => {
    localStorage.setItem('smartfinance_themecolor', 'applefluid-system');
    localStorage.setItem('smartfinance_has_onboarded', 'true');
  });
  await page.emulateMedia({ colorScheme: 'dark' });
  await page.goto('/#/subscriptions');
  await page.getByRole('button', { name: '新增訂閱', exact: true }).click();
  await expect(page).toHaveTitle('SmartFinance');
  await expect(page.getByRole('heading', { name: '選擇服務' })).toBeVisible();
  const screenshotDir = join(process.env.RUNNER_TEMP || '/tmp', 'smartfinance-ui');
  await mkdir(screenshotDir, { recursive: true });
  const shot = (name: string) => page.screenshot({ path: join(screenshotDir, `${info.project.name}-${name}.png`), fullPage: false });
  await shot('picker-dark');
  await page.getByRole('button', { name: '音樂', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Spotify', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Netflix', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: '全部', exact: true }).click();
  await page.getByRole('searchbox', { name: '搜尋服務' }).fill(' OPENAI ');
  await expect(page.getByRole('button', { name: 'ChatGPT', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Spotify', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: '清除搜尋' }).click();
  await page.getByRole('button', { name: 'Netflix', exact: true }).click();
  await expect(page.getByRole('heading', { name: '新增訂閱' })).toBeVisible();
  await expect(page.getByLabel('訂閱名稱')).toHaveValue('Netflix');
  await expect(page.getByLabel('訂閱金額')).toHaveValue('');
  await page.getByLabel('訂閱金額').fill('15.99');
  await page.getByLabel('訂閱幣別', { exact: true }).selectOption('AUD');
  await page.getByLabel('扣款日期').fill('2026-11-03');
  await page.getByRole('heading', { name: '新增訂閱' }).click();
  const details = await page.locator('.sf-sub-disclosure').boundingBox();
  const footer = await page.locator('.sf-sub-footer').boundingBox();
  expect(details!.y + details!.height).toBeLessThanOrEqual(footer!.y);
  await shot('form-dark');
  // Browser Back must return to the picker without losing the unsaved amount.
  await page.goBack();
  await expect(page.getByRole('heading', { name: '選擇服務' })).toBeVisible();
  await page.getByRole('button', { name: 'Netflix', exact: true }).click();
  await expect(page.getByLabel('訂閱金額')).toHaveValue('15.99');
  await expect(page.getByLabel('扣款日期')).toHaveValue('2026-11-03');
  await page.emulateMedia({ colorScheme: 'light' });
  await expect(page.locator('html')).toHaveClass(/theme-applefluid-light/);
  await shot('form-light');
  await page.getByRole('button', { name: '儲存', exact: true }).click();
  await expect(page).toHaveURL(/#\/subscriptions$/);
  await page.getByLabel('訂閱幣別篩選').selectOption('AUD');
  await expect(page.getByText('Netflix', { exact: true })).toBeVisible();
  await page.reload();
  await page.getByLabel('訂閱幣別篩選').selectOption('AUD');
  await page.getByRole('button', { name: '編輯', exact: true }).click();
  await expect(page.getByLabel('訂閱名稱')).toHaveValue('Netflix');
  await expect(page.locator('.sf-sub-identity svg path')).toHaveAttribute('d', /^m5\.398/);
  await expect(page.getByLabel('訂閱金額')).toHaveValue('15.99');
  await expect(page.getByLabel('記帳方式')).toHaveValue('track');
  expect(errors).toEqual([]);
});

test('unknown services can be created and narrow screens retain usable controls', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 700 });
  await page.goto('/#/add-subscription');
  await page.getByRole('searchbox', { name: '搜尋服務' }).fill('My swimming club');
  await expect(page.getByText('搵唔到服務')).toBeVisible();
  await page.getByRole('button', { name: '自訂服務', exact: true }).click();
  await expect(page.getByLabel('訂閱名稱')).toHaveValue('My swimming club');
  await page.getByRole('button', { name: '儲存', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('有效金額');
  await page.getByLabel('訂閱金額').fill('25');
  await page.getByLabel('扣款週期').selectOption('BiWeekly');
  const date = await page.getByLabel('扣款日期').boundingBox();
  const save = await page.getByRole('button', { name: '儲存', exact: true }).boundingBox();
  expect(date!.width).toBeGreaterThan(130);
  expect(date!.y + date!.height).toBeLessThan(save!.y);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: '儲存', exact: true }).click();
  await expect(page.getByText('My swimming club', { exact: true })).toBeVisible();
});
