import { expect, test } from '@playwright/test';
test('subscription trial, custom billing, pause and restore persist', async ({ page }) => {
 await page.clock.setFixedTime(new Date('2026-10-02T12:00:00Z'));
 await page.goto('/#/subscriptions');
 await page.getByRole('button',{name:'新增訂閱',exact:true}).click();
 await page.getByRole('button',{name:'自訂服務',exact:true}).click();
 await page.getByLabel('訂閱名稱').fill('Test plan');
 await page.getByLabel('訂閱金額').fill('30');
 await page.getByLabel('扣款週期',{exact:true}).selectOption('Custom');
 await page.getByLabel('週期間隔').fill('3');
 await page.getByLabel('扣款日期').fill('2026-11-02');
 await page.getByRole('button',{name:'詳細資訊',exact:true}).click();
 await page.getByLabel('免費試用').check();
 await page.getByRole('button',{name:'儲存',exact:true}).click();
 await expect(page.getByText('Test plan',{exact:true})).toBeVisible();
 await expect(page.getByText('試用至 2026-11-02')).toBeVisible();
 await page.getByRole('button',{name:'編輯'}).click();
 await page.getByRole('button',{name:/詳細資訊/}).click();
 await page.getByLabel('訂閱狀態',{exact:true}).selectOption('paused');
 await page.getByRole('button',{name:'更新',exact:true}).click();
 await page.getByRole('button',{name:'已暫停',exact:true}).click();
 await expect(page.getByText('Test plan',{exact:true})).toBeVisible();
 await page.reload();
 await page.getByRole('button',{name:'已暫停',exact:true}).click();
 await page.getByRole('button',{name:'編輯'}).click();
 await page.getByRole('button',{name:/詳細資訊/}).click();
 await page.getByLabel('訂閱狀態',{exact:true}).selectOption('active');
 await page.getByLabel('新價格').fill('35');
 await page.getByLabel('改價生效日').fill('2026-12-01');
 await page.getByRole('button',{name:'更新',exact:true}).click();
 await expect(page.getByText('Test plan',{exact:true})).toBeVisible();
 const download = page.waitForEvent('download');
 await page.getByRole('button',{name:'加入日曆'}).click();
 expect((await download).suggestedFilename()).toBe('subscription-reminders.ics');
});
