import { expect, test, type Page } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import { join } from 'node:path';
async function createCard(page: Page, kind: string, name: string, amount: string) {
 await page.getByRole('button',{name:'新增錢包項目',exact:true}).click();
 await page.getByRole('dialog').getByRole('button',{name:new RegExp(kind)}).click();
 await page.getByLabel('名稱',{exact:true}).fill(name);
 await page.getByLabel('幣別',{exact:true}).selectOption('HKD');
 await page.getByLabel(kind === '儲值卡' ? '現有餘額' : '現有數量').fill(amount);
 await page.getByRole('button',{name:'儲存卡券',exact:true}).click();
 await expect(page.getByRole('heading',{name,exact:true})).toBeVisible();
 await expect(page.getByRole('dialog')).toHaveCount(0);
}
test('stored value payment, edit, deletion and reload recalculate the balance once', async ({page}) => {
 const errors:string[]=[]; page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/#/wallet');
 await createCard(page,'儲值卡','超市卡','100');
 await page.getByRole('button',{name:'增值',exact:true}).click();
 await page.getByLabel('增值金額').fill('20');
 await page.getByRole('button',{name:'確認',exact:true}).click();
 await expect(page.locator('.sf-wallet-balance strong')).toContainText('120');
 await page.getByRole('button',{name:'使用並記帳'}).click();
 await expect(page.getByLabel('付款方式')).not.toHaveValue('');
 await page.getByRole('button',{name:'輸入金額'}).click();
 await page.getByRole('button',{name:'3',exact:true}).click();
 await page.getByRole('button',{name:'0',exact:true}).click();
 await page.getByRole('button',{name:'完成輸入'}).click();
 await page.getByRole('button',{name:'餐飲',exact:true}).click();
 await page.getByRole('button',{name:'儲存',exact:true}).click();
 await expect(page).toHaveURL(/#\/records$/);
 await expect(page.locator('.sf-record-row')).toHaveCount(1);
 await page.getByRole('navigation',{name:'主要導航'}).getByRole('button',{name:'錢包',exact:true}).click();
 await page.getByRole('button',{name:/超市卡/}).click();
 await expect(page.locator('.sf-wallet-balance strong')).toContainText('90');
 await page.reload();
 await expect(page.locator('.sf-wallet-balance strong')).toContainText('90');
 await page.getByRole('button',{name:'查看支出'}).click();
 await page.getByRole('button',{name:'編輯',exact:true}).click();
 await page.getByRole('spinbutton').fill('121');
 await page.getByRole('button',{name:'儲存',exact:true}).click();
 await expect(page.getByRole('alert')).toContainText('餘額不足');
 await page.getByRole('spinbutton').fill('40');
 await page.getByRole('button',{name:'儲存',exact:true}).click();
 await page.getByRole('button',{name:'超市卡',exact:true}).click();
 await expect(page.locator('.sf-wallet-balance strong')).toContainText('80');
 await page.getByRole('button',{name:'查看支出'}).click();
 await page.getByRole('button',{name:'刪除帳目',exact:true}).click();
 await page.getByRole('alertdialog').getByRole('button',{name:'刪除帳目',exact:true}).click();
 await expect(page.locator('.sf-wallet-balance strong')).toContainText('120');
 await page.reload();
 await expect(page.locator('.sf-wallet-balance strong')).toContainText('120');
 expect(errors).toEqual([]);
});

test('count cards, free vouchers, six destinations and overview tabs work in both themes', async ({page},info) => {
 const errors:string[]=[]; page.on('pageerror',e=>errors.push(e.message));
 await page.clock.setFixedTime(new Date('2026-10-03T12:00:00Z'));
 await page.addInitScript(()=>{localStorage.setItem('smartfinance_themecolor','applefluid-system');localStorage.setItem('smartfinance_has_onboarded','true');});
 await page.emulateMedia({colorScheme:'dark'});
 await page.goto('/#/wallet');
 await createCard(page,'次數卡','游泳十次卡','10');
 await page.getByRole('button',{name:'使用',exact:true}).click();
 await page.getByLabel('數量',{exact:true}).fill('2');
 await page.getByRole('button',{name:'確認',exact:true}).click();
 await expect(page.locator('.sf-wallet-balance strong')).toHaveText('8 次');
 await page.getByRole('button',{name:'返回錢包'}).click();
 await createCard(page,'禮券','咖啡禮券','1');
 await page.getByRole('button',{name:'編輯卡券'}).click();
 await page.getByLabel('到期日（可留空）').fill('2026-10-20');
 await page.getByRole('button',{name:'儲存卡券'}).click();
 await expect(page.getByRole('dialog')).toHaveCount(0);
 await expect(page.getByText('每張 HK$ 0')).toBeVisible();
 await page.getByRole('button',{name:'返回錢包'}).click();
 await createCard(page,'儲值卡','超市禮品卡','200');
 await page.getByRole('button',{name:'返回錢包'}).click();
 const dir=join(process.env.RUNNER_TEMP || '/tmp','smartfinance-ui'); await mkdir(dir,{recursive:true});
 for (const theme of ['dark','light'] as const) {
  await page.emulateMedia({colorScheme:theme});
  await page.screenshot({path:join(dir,`${info.project.name}-wallet-${theme}.png`),animations:'disabled'});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 }
 const nav=page.getByRole('navigation',{name:'主要導航'});
 await expect(nav.getByRole('button')).toHaveText(['記帳','總覽','月曆','信用卡','錢包','設定']);
 await nav.getByRole('button',{name:'總覽',exact:true}).click();
 const tabs=page.getByRole('navigation',{name:'總覽分頁'});
 await expect(tabs.getByRole('button')).toHaveText(['摘要','明細','統計']);
 await expect(page.getByRole('heading',{name:'即將扣款及到期'})).toBeVisible();
 await tabs.getByRole('button',{name:'明細',exact:true}).click();
 await expect(page.getByRole('heading',{name:'帳目明細'})).toBeVisible();
 await tabs.getByRole('button',{name:'統計',exact:true}).click();
 await expect(page.getByRole('heading',{name:'報告統計'})).toBeVisible();
 await page.screenshot({path:join(dir,`${info.project.name}-overview.png`),animations:'disabled'});
 await nav.getByRole('button',{name:'月曆',exact:true}).click();
 await expect(page.getByRole('heading',{name:'扣款及到期事項'})).toBeVisible();
 await nav.getByRole('button',{name:'錢包',exact:true}).click();
 await page.getByRole('button',{name:/咖啡禮券/}).click();
 await page.getByRole('button',{name:'使用',exact:true}).click();
 await page.getByRole('button',{name:'確認',exact:true}).click();
 await expect(page.locator('.sf-wallet-balance strong')).toHaveText('0 張');
 await expect(page.getByRole('button',{name:'使用',exact:true})).toBeDisabled();
 await page.getByRole('button',{name:'返回錢包'}).click();
 await expect(page.getByRole('button',{name:/咖啡禮券/})).toHaveCount(0);
 await page.getByLabel('卡券狀態').selectOption('used');
 await expect(page.getByRole('button',{name:/咖啡禮券/})).toBeVisible();
 expect(errors).toEqual([]);
});
